### ISSUE TITLE
Error executing role when user is non root (ubuntu)

### ISSUE THREAD

**Issue by micafer** [indigo-dc/ansible-role-indigovr#2]
Hi @Majlen,

I have tested the new role and there is an error:

All the certificates are generated in a folder that only root user has access.
So in case of using a different user (as in Ubuntu VMs) the role fails:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [node]: FAILED! => {"changed": false, "msg": "Could not find or access '/root/CA/crl.pem' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

**Comment by Majlen** [comment]
Hi @micafer,

will there be a user with some specific username which I can use for this purpose in DEEP infrastructure or should the role stop assuming that it will be run by a specific user and let the authority be somewhat less secure by making it readable by anyone?

There are more issues to resolve though. The role starts the openvpn service (using systemd, upstart or whatever init system the platform uses), which I believe is not permitted for unprivileged users on any platform. I am not sure if Ansible tries sudo when starting the service as unprivileged user fails.

**Comment by micafer** [comment]
Hi @Majlen,

The IM connects with the VMs via SSH using the user provided by the Cloud site. For example in case of Ubuntu S.O.s the default user is "ubuntu". The ansible roles are called with the "become" option that is equivalent to execute a "sudo" command in the remote machines. But no in the local one, so in this line:

https://github.com/indigo-dc/ansible-role-indigovr/blob/master/tasks/centralpoint.yml#L12

You are the user "ubuntu" when reading the file and "root" when writing it.
We have faced this problem in many other roles.

Whe create this yaml to solve it, may be it can help you.
https://github.com/grycap/ansible-role-ssh/blob/master/tasks/sudo_copy.yaml
