### ISSUE TITLE
Error configuring standalone node

### ISSUE THREAD

**Issue by micafer** [indigo-dc/ansible-role-indigovr#3]
Hi @Majlen,

The role is failing at this line:
https://github.com/indigo-dc/ansible-role-indigovr/blob/master/tasks/standalone.yml#L5

This error appears, as the file does not exists:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.0.0.21_1 -> 158.42.105.208]: FAILED! => {"changed": false, "msg": "Could not find or access '/etc/openvpn/certs/INDIGOVR-standalone-vnode-1.localdomain.csr' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

**Comment by Majlen** [comment]
Hi @micafer,

can you tell me which platform or at least which version of Ansible did you test the role on? I did test the role before the pull request and I did not stumble upon this issue. I am also unable to reproduce it now.

**Comment by micafer** [comment]
Hi @Majlen,

I try to deply this TOSCA using the IM:

https://github.com/indigo-dc/tosca-types/blob/vrouter/examples/vrouter_example.yaml

It creates two VMs with ubuntu 16 the first one, the master, is named vnode-0 and the second one, the wn, is named vnode-1.

The configuration of the master VM works correctly but the wn fails because the file '/etc/openvpn/certs/INDIGOVR-standalone-vnode-1.localdomain.cs' does not exists.
